<?php

declare(strict_types=1); require_once dirname(__DIR__).'/config.php'; admin_required(); $pdo=db(); $msg=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf(); $action=(string)($_POST['action']??''); try{
 if($action==='add'){ $name=trim((string)($_POST['name']??'')); $sort=(int)($_POST['sort_order']??0); if($name==='') throw new RuntimeException('동아리명을 입력해 주세요.'); $st=$pdo->prepare("INSERT INTO gift_clubs(name,sort_order,is_active) VALUES(?,?,1)");$st->execute([$name,$sort]);$msg='동아리를 추가했습니다.';}
 if($action==='toggle'){ $id=(int)($_POST['id']??0);$pdo->prepare("UPDATE gift_clubs SET is_active=1-is_active WHERE id=?")->execute([$id]);$msg='상태를 변경했습니다.';}
 if($action==='update'){ $id=(int)($_POST['id']??0);$name=trim((string)($_POST['name']??''));$sort=(int)($_POST['sort_order']??0); if($name==='') throw new RuntimeException('동아리명을 입력해 주세요.');$pdo->prepare("UPDATE gift_clubs SET name=?,sort_order=? WHERE id=?")->execute([$name,$sort,$id]);$msg='수정했습니다.';}
 }catch(Throwable $e){$error=$e->getMessage();}}
$rows=$pdo->query("SELECT c.*, (SELECT COUNT(*) FROM gift_submissions s WHERE s.club_id=c.id) submission_count FROM gift_clubs c ORDER BY sort_order,id")->fetchAll();
?>
<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>동아리설정</title><link rel="stylesheet" href="../assets/style.css"></head><body class="admin-body"><?php include __DIR__.'/_nav.php';?><main class="admin-wrap"><div class="page-head"><div><span class="eyebrow">관리</span><h1>동아리 설정</h1></div></div><?php if($msg):?><div class="alert success"><?=e($msg)?></div><?php endif;?><?php if($error):?><div class="alert danger"><?=e($error)?></div><?php endif;?><section class="card"><h2>동아리 추가</h2><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add"><label>동아리명<input name="name" required placeholder="예: 산악회"></label><label>정렬순서<input name="sort_order" type="number" value="0"></label><button class="btn" type="submit">추가</button></form></section><section class="card"><div class="table-wrap"><table><thead><tr><th>동아리명</th><th>정렬</th><th>제출</th><th>상태</th><th>관리</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><form method="post" class="row-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="id" value="<?=$r['id']?>"><input name="name" value="<?=e($r['name'])?>" required></td><td><input class="sort-input" name="sort_order" type="number" value="<?=$r['sort_order']?>"></td><td><?=number_format((int)$r['submission_count'])?>건</td><td><span class="status <?=$r['is_active']?'on':'off'?>"><?=$r['is_active']?'사용':'중지'?></span></td><td><button class="btn tiny" type="submit">수정</button></form><form method="post" class="inline"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn tiny secondary" type="submit"><?=$r['is_active']?'중지':'사용'?></button></form></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5" class="empty">등록된 동아리가 없습니다.</td></tr><?php endif;?></tbody></table></div></section></main></body></html>
